[package]
edition.workspace = true
name = "guide-cli"
publish = false
version.workspace = true

[dependencies]
burn = { workspace = true, features = ["vision", "train"] }
log = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true }
tracel = { path = "../../crates/tracel", features = ["heat-sdk", "heat-cli"] }

[[bin]]
name = "guide-test"
path = "src/bin/guide-test.rs"
