[package]
edition.workspace = true
name = "guide-cli"
publish = false
version.workspace = true

[dependencies]
burn = { workspace = true, features = ["vision", "wgpu", "train"] }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
tracel = { path = "../../crates/tracel", features = ["heat-sdk", "heat-macros"] }