[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/*",
    "examples/*",
    "xtask",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
readme = "README.md"

[workspace.dependencies]
burn = { git = "https://github.com/tracel-ai/burn", branch = "main" }
# burn = { git = "https://github.com/tracel-ai/burn", tag="v0.13.2", version = "*" }

anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
colored = "2.1.0"
derive-new = { version = "0.6.0", default-features = false }
derive_more = { version = "0.99.18", features = ["display"], default-features = false }
dotenv = "0.15.0"
env_logger = "0.11.3"
log = "0.4.22"
proc-macro2 = { version = "1.0.86" }
quote = "1.0.36"
rand = "0.8.5"
reqwest = "0.12.4"
rmp-serde = "1.3.0"
rstest = "0.19.0"
serde = { version = "1.0.204", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed
serde_json = "1.0.120"
strum = {version = "0.26.3", features = ["derive"]}
syn = { version = "2.0.71", features = ["extra-traits","full"] }
thiserror = "1.0.62"
uuid = { version = "1.9.1", features = ["v4","fast-rng","macro-diagnostics"] }


[profile.dev]
debug = 0 # Speed up compilation time and not necessary.
