[package]
name = "heat-sdk"
repository = "https://github.com/tracel-ai/tracel/tree/main/crates/heat-sdk"
edition.workspace = true
version.workspace = true
readme.workspace = true

[features]
cli = ["dep:heat-macros"]

[dependencies]
burn = { workspace = true, features = ["train"] }
heat-macros = { path = "../heat-macros", version = "0.1.0", optional = true }
macro_magic = { version = "*" }

derive-new = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "json"] }
tungstenite = { version = "0.21.0" }
thiserror = { workspace = true }
tracing = { version = "0.1.40" }
tracing-core = { version = "0.1.32" }
tracing-subscriber = { version = "0.3.18" }

clap = { workspace = true, features = ["derive"] }
strum = { workspace = true }

inventory = "0.3"
once_cell = "1.19"
paste = "1.0"
gensym = "0.1.1"