[package]
name = "tracel"
repository = "https://github.com/tracel-ai/tracel"
edition.workspace = true
version.workspace = true
readme.workspace = true

[features]
default = ["heat-sdk"]
heat-sdk = ["dep:heat-sdk", "dep:heat-sdk-cli-macros"]
heat-sdk-cli = ["dep:heat-sdk-cli", "heat-sdk-cli-macros/build-cli"]

[dependencies]
heat-sdk = { path = "../heat-sdk", version = "0.1.0", optional = true }
heat-sdk-cli = { path = "../heat-sdk-cli", version = "0.1.0", optional = true }
heat-sdk-cli-macros = { path = "../heat-sdk-cli-macros", version = "0.1.0", optional = true }