[package]
name = "tracel"
repository = "https://github.com/tracel-ai/tracel"
edition.workspace = true
version.workspace = true
readme.workspace = true

[features]
heat-sdk = ["dep:heat-sdk"]

[dependencies]
heat-sdk = { path = "../heat-sdk", version = "0.1.0", optional = true }